site_name: PHP Chess
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Read Moves: read-moves.md
  - Data Conversion: data-conversion.md
  - Heuristics: heuristics.md
  - Chess Tutor: chess-tutor.md
  - Play Chess: play-chess.md
