site_name: PHP Chess
pages:
  - Home: index.md
  - Chess\Ascii: ascii.md
  - Chess\Board: board.md
  - Chess\Game: game.md
  - Chess\Heuristics: heuristics.md
  - Chess\Player: player.md
  - Chess\Combinatorics\RestrictedPermutationWithRepetition: combinatorics-restricted-permutation-with-repetition.md
  - Chess\FEN\BoardToStr: fen-board-to-str.md
  - Chess\FEN\StrToBoard: fen-str-to-board.md
  - Chess\FEN\Validate: fen-validate.md
  - Chess\Media\BoardToJpg: media-board-to-jpg.md
  - Chess\Media\BoardToMp4: media-board-to-mp4.md
  - Chess\Media\BoardToPng: media-board-to-png.md
  - Chess\PGN\Movetext: pgn-movetext.md
  - Command Line Interface: cli.md
  - Usage: usage.md
theme: readthedocs
